#!/bin/sh
#######
### Setup Traffic Control to limit outgoing bandwidth for Plex Media Server.
### Sourced from
### http://www.cyberciti.biz/faq/linux-traffic-shaping-using-tc-to-control-http-traffic/
### Script originally from: https://forums.plex.tv/discussion/39823/howto-limit-plex-media-server-bandwidth-on-linux
#######
# place in /etc/init.d
# sudo update-rc.d plex-throttling defaults

### Sleep for a second
sleep 1

### Delete all TC rules for eth0 
/sbin/tc qdisc del dev eth0 root 2> /dev/null || /bin/true

### Activate queueing discipline
/sbin/tc qdisc add dev eth0 root handle 1:0 htb

### Define class allowed 720kbit burst to 720kbit (kbps=kiloBYTES)
/sbin/tc class add dev eth0 parent 1:0 classid 1:10 htb rate 720kbit ceil 720kbit prio 0

### Create iptables mangle rule for outgoing port 32400 (Plex Media Server)
/sbin/iptables -A OUTPUT -t mangle -p tcp --sport 32400 ! --dst 10.2.2.0/24 -j MARK --set-mark 10

### Assign the rule to the proper qdisc
/sbin/tc filter add dev eth0 parent 1:0 prio 0 protocol ip handle 10 fw flowid 1:10

### Notes
## show TC rules
# /sbin/tc -s -d class show dev eth0
## Show iptables mangle rules
# /sbin/iptables -t mangle -n -v -L
## Show actual bandwidth being used on 32400
# watch -n 1 /sbin/tc -s -d class show dev eth0
